spring:
  application:
    name: Game Store POC
  datasource:
    username: username
    password: passord
    url: jdbc:postgresql://localhost:5432/game-store-dev-db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: auto
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
    contexts: local
    parameters:
      data-file-prefix: local
      catalog-name: integratordata
  redis:
    database: 0
    host: localhost
    port: 6379
    password: password
    timeout: 60000